site_name: limyel's wiki
theme: material
nav:
  - 关于: index.md
  - Java: java.md
  - Python: python.md
  - Spring: spring.md
  - SpringMVC: springmvc.md
  - SpringBoot: springboot.md
  - MyBatis: mybatis.md
  - Elasticsearch: elasticsearch.md
  - MySQL: mysql.md
  - Kafka: kafka.md
  - Go: go.md
  - Vue: vue.md
  - Linux: linux.md
  - Windows: windows.md
  - IDEA: idea.md
  - NeoVim: neovim.md